spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/taxi_user_db
    username: user_admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Проверяет, что таблицы в БД совпадают с твоими Entity
    show-sql: true        # Будешь видеть все INSERT в консоли IDEA
    properties:
      hibernate:
        format_sql: true  # Делает SQL в консоли читаемым
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:                 # Убрали лишнее слово spring: перед flyway
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration  # Путь к твоим SQL скриптам