services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  trip-db:
    image: postgres:15
    container_name: trip-db
    environment:
      POSTGRES_DB: taxi_trip_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: your_password
    ports:
      - "5433:5432" # Пробрасываем на другой порт хоста, чтобы не было конфликта