-- Создание таблицы для поездок
CREATE TABLE IF NOT EXISTS trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL,
    driver_id BIGINT,
    status VARCHAR(20) NOT NULL,
    start_point VARCHAR(255) NOT NULL,
    end_point VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Если у тебя есть пользователи или водители в этой же базе:
CREATE TABLE IF NOT EXISTS persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL, -- 'DRIVER', 'PASSENGER'
    rating DOUBLE PRECISION DEFAULT 5.0
);